In [40]:
import numpy as np
mynumpy=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(mynumpy)

#studi kasusnya bagaimana cari sy mengetahui dimensi data menggunakan library
print('dimensi data dari mynumpy: ',mynumpy.ndim)

#studi kasusnya bagiamana cara saya mengetahui berapa jumlah baris dan columnya
print('baris dan column: ',mynumpy.shape)

#bagimana cara sy mengetahui type data yang digunakan di dalam array 
print('tipe data dalam array: ',mynumpy.dtype) # output int 32 bit
# bagiamana cara sy mengetahui totoal byte yang digunakan
print('total byte yang digunakan: ',mynumpy.nbytes)

#bagiaman cara sy mengakses data index ke 1 dari 2 sampai seterusnya
print('akese dari index 1: ',mynumpy[1][2:4])

#bagaimana cara mengetahui item sizenya
print(mynumpy.itemsize)

[[1 2 3 4 5]
 [6 7 8 9 0]]
dimensi data dari mynumpy:  2
baris dan column:  (2, 5)
tipe data dalam array:  int32
total byte yang digunakan:  40
akese dari index 1:  [8 9]
4


In [13]:
# Materi Slicing array
# [start stop step]
# studi kasunya bagiamana jika saya menampilkan data dengan range 10
mynumpy=np.array(range(10))
print(mynumpy)

# # bagaimana jika saya menampikan data dengan setp data 2 dan stop 6 mulai dari 0
print(mynumpy[1:6:2])

# # bagiamana jika array multidimensi
# print('multidimensi: ',mynumpy[1:,2:])



[0 1 2 3 4 5 6 7 8 9]
[1 3 5]


In [21]:
# studi kasusnya bagiamana saya bisa menampilkan array 2 dimensi dengan baris 2 dan col 5
print(mynumpy.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
# Studikasus misalnya kita memiliki 2 buah array dan saya akan menggabungan kedua buah array ts
my_numpy1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
my_numpy2=np.array([[1,2,3,1,4],[2,3,5,3,5]])

print('hasil gabunganan: ',np.concatenate([my_numpy1,my_numpy2]))

hasil gabunganan:  [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 2 3 1 4]
 [2 3 5 3 5]]


In [28]:
# Materi series pada library pandas
# studi kasus buat sebuah variabel dengan nama x yang menyimpan data series
import pandas as pd 
x=pd.Series([4,5,6,7,8])
# print(x)
# studi kasus series memiliki index dari 0 sampai 1 nah bagaimana cara saya supaya data tersebut sy ubah berdasarkan abjad
x.index=['a','b','c','d','e']
print(x)
print(type(x))

# Catatan penting perhatikan jumlah indexnya harus sama dengan jumlah datanya


a    4
b    5
c    6
d    7
e    8
dtype: int64
<class 'pandas.core.series.Series'>


In [4]:
#Masuk ke materi membaca file menggunakan pandas file yang di baca csv
# ada 2 method yng sering digunakan untuk membaca file csv dapat menggunakan read_csv() sedangan untuk exel dapa menggunakan read_exel()
#method yang harus di pahami di pandas
# head()=> menampilkan 5 data secara default()
#tail()=> meihat 5 data terakhir
# info() => memberikan ringkasan dari data
# describe() => method yang memberikan kesimpulan secara deskriptid
import pandas as pd
datacovid=pd.read_csv('datacovid.csv')
print(datacovid.head(5))


  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          1.0        1.0   
1      AFG      Asia  Afghanistan  2020-02-25          1.0        0.0   
2      AFG      Asia  Afghanistan  2020-02-26          1.0        0.0   
3      AFG      Asia  Afghanistan  2020-02-27          1.0        0.0   
4      AFG      Asia  Afghanistan  2020-02-28          1.0        0.0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...   
1                 NaN           NaN         NaN                  NaN  ...   
2                 NaN           NaN         NaN                  NaN  ...   
3                 NaN           NaN         NaN                  NaN  ...   
4                 NaN           NaN         NaN                  NaN  ...   

   gdp_per_capita  extreme_poverty  cardiovasc_death_rate  \
0        1803.987              NaN   

In [33]:
# studi kasus bagiaman menamilkan 7 data terakhir saja dari data csv
print(datacovid.tail(7))

      iso_code continent  location        date  total_cases  new_cases  \
84090      ZWE    Africa  Zimbabwe  2021-04-19      37859.0      108.0   
84091      ZWE    Africa  Zimbabwe  2021-04-20      37875.0       16.0   
84092      ZWE    Africa  Zimbabwe  2021-04-21      37980.0      105.0   
84093      ZWE    Africa  Zimbabwe  2021-04-22      38018.0       38.0   
84094      ZWE    Africa  Zimbabwe  2021-04-23      38045.0       27.0   
84095      ZWE    Africa  Zimbabwe  2021-04-24      38064.0       19.0   
84096      ZWE    Africa  Zimbabwe  2021-04-25      38086.0       22.0   

       new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
84090              78.857        1553.0         0.0                1.571  ...   
84091              77.857        1554.0         1.0                1.571  ...   
84092              87.286        1555.0         1.0                1.000  ...   
84093              85.143        1555.0         0.0                0.714  ...   
84

In [5]:
# studi kasus bagimana ketika kita ingin mengetahui informasi dari datacovid.csv tersebut
print(datacovid.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84097 entries, 0 to 84096
Data columns (total 59 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   iso_code                               84097 non-null  object 
 1   continent                              80031 non-null  object 
 2   location                               84097 non-null  object 
 3   date                                   84097 non-null  object 
 4   total_cases                            82077 non-null  float64
 5   new_cases                              82075 non-null  float64
 6   new_cases_smoothed                     81074 non-null  float64
 7   total_deaths                           72453 non-null  float64
 8   new_deaths                             72611 non-null  float64
 9   new_deaths_smoothed                    81074 non-null  float64
 10  total_cases_per_million                81633 non-null  float64
 11  ne

In [35]:
# studi kasus bagaimana memberikannya sebuah deskripsi datacovid.csv tersebut
print(datacovid.describe())

        total_cases      new_cases  new_cases_smoothed  total_deaths  \
count  8.207700e+04   82075.000000        81074.000000  7.245300e+04   
mean   8.058046e+05    5718.143210         5692.332794  2.260774e+04   
std    5.579207e+06   35538.797526        34813.794708  1.335640e+05   
min    1.000000e+00  -74347.000000        -6223.000000  1.000000e+00   
25%    9.070000e+02       2.000000            6.857000  4.400000e+01   
50%    1.010500e+04      69.000000           84.286000  3.090000e+02   
75%    1.077430e+05     755.000000          784.678250  3.000000e+03   
max    1.471896e+08  899755.000000       826374.286000  3.109247e+06   

         new_deaths  new_deaths_smoothed  total_cases_per_million  \
count  72611.000000         81074.000000             81633.000000   
mean     137.791588           121.926315              9810.522168   
std      751.191619           687.112308             18872.369979   
min    -1918.000000          -232.143000                 0.001000   
25%   